# Data Preprocessing Tools

## Importing the libraries

In [72]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [73]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [74]:
print(X)

[['India' 44.0 72000.0]
 ['Nepal' 27.0 48000.0]
 ['Tibet' 30.0 54000.0]
 ['Nepal' 38.0 61000.0]
 ['Tibet' 40.0 nan]
 ['India' 35.0 58000.0]
 ['Nepal' nan 52000.0]
 ['India' 48.0 79000.0]
 ['Tibet' 50.0 83000.0]
 ['India' 37.0 67000.0]]


In [75]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [76]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [77]:
print(X)

[['India' 44.0 72000.0]
 ['Nepal' 27.0 48000.0]
 ['Tibet' 30.0 54000.0]
 ['Nepal' 38.0 61000.0]
 ['Tibet' 40.0 61000.0]
 ['India' 35.0 58000.0]
 ['Nepal' 38.0 52000.0]
 ['India' 48.0 79000.0]
 ['Tibet' 50.0 83000.0]
 ['India' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [78]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [79]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 27.0 48000.0]
 [0.0 0.0 1.0 30.0 54000.0]
 [0.0 1.0 0.0 38.0 61000.0]
 [0.0 0.0 1.0 40.0 61000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 38.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [80]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [81]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [82]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2)

In [83]:
print(X_train)

[[1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 30.0 54000.0]
 [0.0 1.0 0.0 38.0 61000.0]
 [0.0 1.0 0.0 38.0 52000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 50.0 83000.0]]


In [84]:
print(X_test)

[[0.0 0.0 1.0 40.0 61000.0]
 [0.0 1.0 0.0 27.0 48000.0]]


In [85]:
print(y_train)

[1 0 1 0 0 0 1 0]


In [86]:
print(y_test)

[1 1]


## Feature Scaling

In [87]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [88]:
print(X_train)

[[1.0 0.0 0.0 -0.7881104062391007 -0.7213204519277457]
 [1.0 0.0 0.0 0.6304883249912805 0.5817100418772143]
 [1.0 0.0 0.0 1.260976649982561 1.2332252887796944]
 [0.0 0.0 1.0 -1.5762208124782013 -1.093614878729163]
 [0.0 1.0 0.0 -0.31524416249564025 -0.4420996318266829]
 [0.0 1.0 0.0 -0.31524416249564025 -1.2797620921298716]
 [1.0 0.0 0.0 -0.47286624374346037 0.11634200837544287]
 [0.0 0.0 1.0 1.5762208124782013 1.6055197155811116]]


In [89]:
print(X_test)

[[0.0 0.0 1.0 0.0 -0.4420996318266829]
 [0.0 1.0 0.0 -2.0490870562216617 -1.6520565189312888]]
